### ISSUE TITLE
Time show in UTC in event details even though GMT+2 is set in settings

### ISSUE THREAD

**Issue by Pauligrinder** [marcoancona/MineTime#101]
This issue only appears on our Google Family-calendar, which is forced to UTC (it can't be changed, I guess Google has thought that having it in UTC is most convenient in order to support families all over the world or something ...). For example today my son has an event at 17:30 and it shows just right in the actual calendar view, but when I open its' details it shows as 15:30 (GMT+00:00), which is a bit confusing. I guess if the "original" calendar time is to be shown, it should be inside the parenthesis along with the timezone information if it needs to be shown at all - the Google Calendar Android-app for example doesn't show any timezone info other than in the edit-view.

![calendar_bug](https://user-images.githubusercontent.com/5802137/51981224-27562a80-249b-11e9-87b8-215ddfc23be3.jpg)

**Comment by marcoancona** [comment]
Thanks for the feedback. Indeed the sidebar shows the time in the timezone of the event. We will consider adding also the local timezone soon.

**Comment by benkap** [comment]
Great app, beautiful UI.. But the correct timezone on Calendar app is a requisite since this is the most basic information you need from a Calendar.
Any update on this feature?
Thanks!

**Comment by marcoancona** [comment]
The new release (1.6.3) shows now both times if the event timezone is different than the calendar timezone.

**Comment by benkap** [comment]
I installed the 1.6.3 (Ubuntu 18.04) and still i have the same problem with timezone.. In the profile page i have set the timezone to GMT+3 and the OS also set to the same timezone but recurrent weekly event are seen on 8:00AM instead of 11:00AM.

I have two calendars configured: gmail and 365 (The recurrent event is on the 365 account but maybe the problem is also on the gmail account not sure yet).

Using Android with google calendar I can see both accounts with the correct times so i know that the event should be on 11:00..

Any ideas?

**Comment by benkap** [comment]
I see the wrong time on both where on the sidebar i see the two timezones (GMT-0 and GMT-3, I'll try attaching screenshots).

Not sure how to check the timezone on an event. I think since i didn't created it I can't see (or modify any settings on it).
![Screenshot from 2019-10-17 17-19-07](https://user-images.githubusercontent.com/13090561/67017564-a0b5ac00-f102-11e9-99ac-aaf4b36abe25.png)
![Screenshot from 2019-10-17 17-19-26](https://user-images.githubusercontent.com/13090561/67017577-a4e1c980-f102-11e9-8e7d-9dc5b598de5e.png)

Thanks!
