### ISSUE TITLE
How to remove exe from my pc

### ISSUE THREAD

**Issue by louiscoetzee** [marcoancona/MineTime#145]
Why am I unable to remove the exe from my pc? I think this app is malicious. I delete the exe and it reappears. 

C:\Users\xxxx\AppData\Local\MineTime\app-1.5.1\MineTime.exe as well as the resources folder and the other files.

Kindly please advise.

**Comment by marcoancona** [comment]
To uninstall MineTime on Windows, just follow the normal procedure to uninstall apps from the system settings: https://support.microsoft.com/en-us/help/4028054/windows-10-repair-or-remove-programs
The executable reappears because there is another service, responsible for the auto-update, that repairs it. This is simply not the way to uninstall an application on Windows.

**Comment by marcoancona** [comment]
I close this due to lack of activity.

**Comment by sergeevabc** [comment]
Windows 7 user.
Do you know how painful it is to get rid of you app here?
`MinetimeSchedulingService.exe` stays in memory after official uninstall procedure.
