### ISSUE TITLE
Cannot create new events, events not synced, and problem with calendar pane from version 1.7.3

### ISSUE THREAD

**Issue by flg** [marcoancona/MineTime#164]
Linux versions. Tested with RPMs and AppImages.

On the left hand pane, the calendar tab shows the waiting symbols spinning forever, for all calendars (1 exchange, 2 google). I suppose it means there is a connection issue.

And indeed I cannot create new events on any of the calendars. When I click in the timetable, the widget for the new event shows up, I can fill it in, click save : a waiting symbol appears and keeps spinning for ever. I checked in Google Calendar and Exchange and the events are indeed not created.

I tried relinking the calendars, it seems to work (shows "starting syncing..." and then it disappears) but I still cannot create events.

I created events in the calendars via another interface and the new events do not appear in Minetime. Neither after a relink, nor after an application restart.

It seems synchronisation is broken. In the following file, the log messages triggered by a relink attempt.
[mt.txt](https://github.com/marcoancona/MineTime/files/3956408/mt.txt)

**Comment by marcoancona** [comment]
Thanks for reporting. First, notice that the latest version is 1.7.4 now.

Your problem seems to be caused by a failure of accessing the account credentials with `keytar` on your system. Actually, on Linux keytar should not be enabled unless you have used it in the past.

While we investigate the issue, there is a manual workaround:
- close MineTime
- open `~/.config/MineTime/config.json` with a text editor 
- set the `useKeytar` field to `false` and save
- restart MineTime (you will need to relink your accounts but now the synchronization should work).

Alternatively, you can also delete `config.json` but this will force you to go through the registration process in order to use MineTime.

**Comment by flg** [comment]
Workaround worked fine. Thank you very much.
