### ISSUE TITLE
Max alert notification 28 days

### ISSUE THREAD

**Issue by DOFfactory** [marcoancona/MineTime#186]
Currently the alert notification is maxed out to 28 days. It does not make sense, especially if one is able to add multiple alerts. What if I have a long-term project where I need to get back to it regularly? It would be great to be able to add alerts every month (repeatedly), and definitely not to limit it to 28 days (not even 31 days).

**Comment by marcoancona** [comment]
Could you please elaborate on this use case? Do you have a calendar event indicating the deadline for a long-term project? What actions do you take when you get an alert notification about this event? While I kind of understand the problem here, this seems a stretch of what event notifications had been designed for. Would it work to add a recurrent event (or multiple events) to book your time to work on that given project?

**Comment by DOFfactory** [comment]
Try to make an alert for any event that is greater than 28 days. You will get the following message:

![image](https://user-images.githubusercontent.com/10846169/83156698-03444100-a103-11ea-984c-e17ea4ebd163.png)

**Comment by marcoancona** [comment]
This limitation is removed in 1.8.0.
