### ISSUE TITLE
Calendars do not load

### ISSUE THREAD

**Issue by saltymedic** [marcoancona/MineTime#98]
This is my first time trying your software. I'm on an updated Manjaro Linux KDE distro

I tried adding two different Gmail accounts and a Nextcloud account.

Nothing ever shows up on the calendar and all I see next to the calendar names (which it loaded all the calendar names for each account) is a bunch of spinning wheels.

What could i have forgotten to do?

Thanks

Jason

**Comment by saltymedic** [comment]
working now

**Comment by saltymedic** [comment]
I had to reinstall Manjaro and Minetime and I am back to having the same problem of the calendars not ever loading. Any idea what I can do to get calendars to load? This is for two separate Google acccounts and a Nexcloud CalDAV. Nothing ever imports and there is a spinning circle next to each calendar name that never stops.
![screenshot_20190203_163537](https://user-images.githubusercontent.com/18824694/52184545-c21f7380-27d1-11e9-8f88-255969e1a3c8.png)

**Comment by marcoancona** [comment]
This is the same distro you used back in December, isn't it? Did you do anything special to make it sync when the problem was solved the first time? In particular, please make sure `libsecret` is installed in your system.

**Comment by otisdog8** [comment]
Also having the problem. I'm using Arch Linux KDE with MineTime 1.4.10 installed using debtap. I have a Nextcloud CalDAV with four calendars that is not syncing, with the same spinning circle issue.

**Comment by otisdog8** [comment]
I installed gnome-keyring and seahorse, and now it works.

**Comment by saltymedic** [comment]
> I installed gnome-keyring and seahorse, and now it works.

Thank you @otisdog8 

After installing both of those packages Minetime is working for me now.

**Comment by marcoancona** [comment]
Thanks for pointing out! I'll update the readme.

**Comment by ithinkmatt** [comment]
I am unable to add my G Suite account on my laptop: Ubuntu Budgie 18.04, 18.10, 19.04 (current). It goes through the process to add the account, but after allowing at Google no account is added. I have tried to remove the package and reinstall, as well. That doesn't fix the issue.

I am able to remove my G Suite account on my desktop: Ubuntu Budgie 18.04, 18.10, 19.04 (current). Then add the account back without issue.

I have never been able to add the G Suite account to my laptop. I've been through the items noted on Github, but it hasn't resolved anything.

I do have gnome-keyring and seahorse. All dependent packages are present.

**Comment by marcoancona** [comment]
That is interesting, so you have the exact same operating system but on your laptop it fails to add the account. When you say "no account is added" do you mean that the account does not even appear on the left sidebar of the Calendars settings tab?
Do you have some proxy/firewall active on your wifi network? You can try to type `analysis` on the assistant request and check the logs for anything suspicious.

**Comment by ithinkmatt** [comment]
@marcoancona 

I am back. I am still unable to add my Google G Suite calendar to MimeTime. Thank you for the tip on using analysis to check the logs.

I decided to update to Ubuntu 19.04, then tried again. Unfortunately, I am still unable to add my Google G Suite calendar on my laptop, but still have no issues with my Ubuntu desktop.

---

Here's a breakdown of I is happening (screenshosts attached).

- 1: I am already logged into my MineTime account, I clicked Calendars, Then clicked Google to Add account

- 3: MineTime popup message about Google browser redirect

- 4: Login to Google account, Browser window shows Google confirmation page to allow MineTime access to my Google account. Clicked Allow. Notice on the screenshot attached the status bar says "Waiting for localhost..." By the way, MineTime is already allowed to access my Google account.

- 5: After an extended period of time the browser redirects to localhost:42291/?code={additional-characters-shown} with the following text: "Authorization failed. Please try again or contact us if the problem persists."

- 6: After the authorization failed message in the browser, the MineTime popup displays the following text: "An error occurred during the authorization process. Please try again or contact us if the problem persists."

---

Here are three lines from the 41,000+ lines in the Log file (~/.config/MineTime/logs/log.log)

- 2019-04-28T01:55:39.184Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T01:55:41.137Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T01:55:42.259Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]

---

I have even tried removing MineTime from being authorized at Google. Removing MineTime from being authorized at Google does not change anything when attempting to complete the authorization process.

I also noticed that I can remove and --purge the app from my laptop. But, when reinstalling I am already logged into my MineTime account.

The authorization issue still happens with the .AppImage file.

---

At this point I am stuck. I am hoping that at some point this can be resolved so I can continue using MineTime.

Any help would be very much appreciated.

Thanks,

Matt

![1_MineTime-Account](https://user-images.githubusercontent.com/40709357/56857318-9542ae80-6931-11e9-85dc-c3a9d5553f81.png)

![2_MineTime-Add-Google](https://user-images.githubusercontent.com/40709357/56857319-9bd12600-6931-11e9-90b6-40555c9c5aba.png)

![4_MineTime-Google-Failed](https://user-images.githubusercontent.com/40709357/56857325-ae4b5f80-6931-11e9-949b-ff99fd9e0855.png)

![3_MineTime-Google-Allow-1](https://user-images.githubusercontent.com/40709357/56857326-b1465000-6931-11e9-8b71-6789b42a6f97.png)

![5_MineTime-Google-Error](https://user-images.githubusercontent.com/40709357/56857322-ab506f00-6931-11e9-9df2-3a0e6eac39d0.png)

**Comment by marcoancona** [comment]
Can you please check the *frontend* console for errors? When you type "analysis", the log file is displayed but you should also see a console appearing on the right-hand side of the application view. Any error in red there during the authorization process?

**Comment by ithinkmatt** [comment]
I haven't been able to check on the frontend console on my laptop yet, but
decided to test my desktop since I am currently at the office. I
uninstalled and reinstalled MineTime to add the account. The account ads
without issue.

---

Here's a breakdown of what I did on my desktop (no screenshots provided):

1: I am already logged into my MineTime account, I clicked Calendars, Then
clicked Google to Add account

3: MineTime popup message about Google browser redirect shown

4: Login to Google account, Browser window shows Google confirmation page
to allow MineTime access to my Google account. Clicked Allow. Status bar
says "Waiting for localhost..." for a very SHORT period of time.

5: After a brief wait the browser redirects to
localhost:40077/?code={additional-characters-shown} with the following
text: "MineTime is authorized. You can safely close this page."

6: After successful authorization, the MineTime popup displays the
following text: "Done"

---

Here's the Log from my desktop:

- 2019-04-28T18:01:44.542Z - info:
- 2019-04-28T18:01:44.542Z - info: *********************
- 2019-04-28T18:01:44.542Z - info: App ready
- 2019-04-28T18:01:44.542Z - info:  0=/opt/MineTime/minetime
- 2019-04-28T18:01:44.543Z - info: *********************

- 2019-04-28T18:01:44.628Z - info: Waiting for open db connection on port
50227
- 2019-04-28T18:01:44.628Z - info: Connecting [mongodb://
127.0.0.1:50227/minetime]
- 2019-04-28T18:01:45.161Z - info: Connecting [mongodb://
127.0.0.1:50227/minetime]
- 2019-04-28T18:01:45.180Z - info: Database online!
- 2019-04-28T18:01:45.183Z - info: Authorizing mongo...
- 2019-04-28T18:02:50.632Z - info: Creating Google account...

---

Based on the log information, it looks to me like the laptop is never
getting past connecting to mongodb.

I'll also check the frontend console on my laptop for errors and post them.

Thanks,

Matt

**Comment by ithinkmatt** [comment]
I haven't been able to check on the frontend console on my laptop yet, but decided to test my desktop since I am currently at the office. I uninstalled and reinstalled MineTime to add the account. The account ads without issue.

---

Here's a breakdown of what I did on my desktop (no screenshots provided):

1: I am already logged into my MineTime account, I clicked Calendars, Then clicked Google to Add account

3: MineTime popup message about Google browser redirect shown

4: Login to Google account, Browser window shows Google confirmation page to allow MineTime access to my Google account. Clicked Allow. Status bar says "Waiting for localhost..." for a very SHORT period of time.

5: After a brief wait the browser redirects to localhost:40077/?code={additional-characters-shown} with the following text: "MineTime is authorized. You can safely close this page."

6: After successful authorization, the MineTime popup displays the following text: "Done"

---

Here's the Log from my desktop:

- 2019-04-28T18:01:44.542Z - info:  
- 2019-04-28T18:01:44.542Z - info: *********************
- 2019-04-28T18:01:44.542Z - info: App ready
- 2019-04-28T18:01:44.542Z - info:  0=/opt/MineTime/minetime
- 2019-04-28T18:01:44.543Z - info: *********************

- 2019-04-28T18:01:44.628Z - info: Waiting for open db connection on port 50227
- 2019-04-28T18:01:44.628Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T18:01:45.161Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T18:01:45.180Z - info: Database online!
- 2019-04-28T18:01:45.183Z - info: Authorizing mongo...
- 2019-04-28T18:02:50.632Z - info: Creating Google account...

---

Based on the log information, it looks to me like the laptop is never getting past connecting to mongodb.

I'll also check the frontend console on my laptop for errors and post them.

Thanks,

Matt

**Comment by ithinkmatt** [comment]
I am currently testing on my laptop again. I reinstalled MineTime and attempted setup.

---

Here is the text from the frontend console:

- Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
/opt/MineTime/resources/app.asar/node_modules/statorgfc/build/statorgfc.js:84

- Overwriting existing state key searchActive
connectComponentState @ /opt/MineTime/resources/app.asar/node_modules/statorgfc/build/statorgfc.js:84
/opt/MineTime/resources/app.asar/node_modules/statorgfc/build/statorgfc.js:84

- Overwriting existing state key editingEvent
connectComponentState @ /opt/MineTime/resources/app.asar/node_modules/statorgfc/build/statorgfc.js:84
survey.component.js:33

- Install listener on modal.analytics.close
cdn.logrocket.io/logger.min.js Failed to load resource: net::ERR_NAME_NOT_RESOLVED
app.container.js:32 LogRocket on
/opt/MineTime/resources/app.asar/node_modules/logrocket/dist/build.umd.js:325 LogRocket: script could not load. Check that you have a valid network connection.
shim @ /opt/MineTime/resources/app.asar/node_modules/logrocket/dist/build.umd.js:325
google.modal.component.js:101

- Error: invalid_grant
  at createError (/opt/MineTime/resources/app.asar/node_modules/axios/lib/core/createError.js:16)
  at settle (/opt/MineTime/resources/app.asar/node_modules/axios/lib/core/settle.js:18)
  at IncomingMessage.handleStreamEnd (/opt/MineTime/resources/app.asar/node_modules/axios/lib/adapters/http.js:201)
  at emitNone (events.js:111)
  at IncomingMessage.emit (events.js:208)
  at endReadableNT (_stream_readable.js:1056)
  at _combinedTickCallback (internal/process/next_tick.js:138)
  at process._tickCallback (internal/process/next_tick.js:180)

---

Here is the Log after re-installing:

- Over 55,600 lines in the log for Connecting [mongodb://127.0.0.1:50227/minetime]. Truncated lines below:

- 2019-04-28T19:28:03.442Z - info:  
- 2019-04-28T19:28:03.443Z - info: *********************
- 2019-04-28T19:28:03.443Z - info: App ready
- 2019-04-28T19:28:03.443Z - info:  0=/opt/MineTime/minetime
- 2019-04-28T19:28:03.443Z - info: *********************

- 2019-04-28T19:28:03.548Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:28:03.549Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:04.092Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:04.596Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:05.098Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:05.600Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.044Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:28:06.045Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.109Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:28:06.109Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.111Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.144Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:28:06.144Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.393Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:28:06.393Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.547Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:28:06.620Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:28:06.621Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
  ~~~
- 2019-04-28T19:33:23.273Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:33:23.347Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:33:23.348Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:33:23.470Z - info: Waiting for open db connection on port 50227
- 2019-04-28T19:33:23.471Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:33:23.567Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T19:33:23.576Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
  ~~~
- 2019-04-28T20:12:54.434Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T20:12:54.639Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
- 2019-04-28T20:12:54.640Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]

---

Thanks,

Matt

**Comment by ithinkmatt** [comment]
Issue resolved!

- 1: Uninstalled the pkg using "sudo apt-get remove --purge minetime".
- 2: Manually deleted ALL files in .config/MineTime/
- 3: Emptied Trash
- 4: Reinstalled minetime.deb
- 5: Performed setup, everything worked as expected

---

Thanks,

Matt

**Comment by marcoancona** [comment]
Thanks,
we are looking into that to understand what was the problem. Glad it is solved for you now.

**Comment by ithinkmatt** [comment]
@marcoancona You're welcome! I posted in the event someone has the same issue in the future. My guess is the mongodb was corrupt. Standard command line pkg removal wasn't deleting all files or the database. A manual delete allowed the database to be completed removed and a new database created when reinstalled.

**Comment by johanncopeland** [comment]
I might have more information and another quick fix.

I was facing the same issue on Fedora but had no luck with reinstalling and/or deleting the config directory. 

What I did was set the .desktop file to open MineTime in terminal and found that mongodb was giving me this error:
```
Failed global initialization: BadValue: Invalid or no user locale set. Please ensure LANG and/or LC_* environment variables are set correctly.
```
This error was not present in the logs, however. 

I found a solution for this error which sets the locales (for a single user) [on StackOverflow:](https://stackoverflow.com/questions/26337557/badvalue-invalid-or-no-user-locale-set-please-ensure-lang-and-or-lc-environme)
```
$ echo "export LC_ALL=C" >> ~/.bashrc
```
I then logged out and logged in and everything is working fine.

**Comment by sistemasinde** [comment]
> Issue resolved!
> 
>     * 1: Uninstalled the pkg using "sudo apt-get remove --purge minetime".
> 
>     * 2: Manually deleted ALL files in .config/MineTime/
> 
>     * 3: Emptied Trash
> 
>     * 4: Reinstalled minetime.deb
> 
>     * 5: Performed setup, everything worked as expected
> 
> 
> Thanks,
> 
> Matt

not working for Manjaro 21 5.9-16 :(
